### ISSUE TITLE
Linux 수동 설치법 표기

### ISSUE THREAD

**Issue by LJLee37** [ezwebex/ezwebex-electron#1]
릴리즈에서 리눅스는 수동설치가 필요하다고 하셨는데 해당 설치법이 나와있지 않네요. 소스를 받아서 npm install npm start 하는 것과 같이 설치법을 적어주셨으면 합니다.

**Comment by Alex4386** [comment]
네, README.md 에 명시할 수 있도록 수정하겠습니다.

**Comment by Alex4386** [comment]
Issue Resolved via commit 4ea7fe54c657ac0f8d489de0d167dc4a5de00e23, Closing Issue.
