### ISSUE TITLE
로그인할때 에러가 발생합니다

### ISSUE THREAD

**Issue by hoo0681** [ezwebex/ezwebex-electron#2]
![KakaoTalk_20200831_092854518](https://user-images.githubusercontent.com/47309894/91673018-d6258580-eb6c-11ea-8642-ce573d039bf3.png)

![주석 2020-08-31 093613](https://user-images.githubusercontent.com/47309894/91673123-85625c80-eb6d-11ea-8408-b6cb4ab38906.jpg)

null인 값이 있는 수업이 있어서 그런듯 합니다

**Comment by Alex4386** [comment]
감사합니다! 1.1.1 버전에서 수정하겠습니다!

**Comment by Alex4386** [comment]
1.2.0 으로 버전 수정

**Comment by Alex4386** [comment]
Resolved via commit d18f676b24d37d430b3cb9cb001c43d36cb94feb, Closing Issue.
